name: Build MAUI Project

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
# ********************** NET 6 MAUI app | Windows build ************************* #
  maui-on-windows:
    runs-on: windows-latest
    env:
      ProjectPath: src/MAUI/HelloMaui/HelloMauiWinUI3.csproj
      SolutionPath: src/MAUI/DemoAppWinUI3.sln
      NuGetConfigPath: src/MAUI/NuGet.Config
      BuildConfig: Debug
      IsRunningOnCI: true
      DotNetVersion: 6.0.100-preview.5.21302.13
      DotNet.Cli.Telemetry.OptOut: true
      MauiCheckVersion: 0.5.6
      MauiCheckManifest: https://raw.githubusercontent.com/Redth/dotnet-maui-check/main/manifests/maui-dev.manifest.json
      Actions_Allow_Unsecure_Commands: true # Allows env variables on the job-level
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Generate version number
      shell: pwsh
      run: |
        $buildDay = Get-Date -Format "yyyy.Mdd"
        $ver = $buildDay + "." + $env:GITHUB_RUN_NUMBER + ".0"
        echo "APP_VERSION=$ver" >> $GITHUB_ENV

    - name: Install .NET 6 SDK
      shell: pwsh
      run: |
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile dotnet-install.ps1
        & .\dotnet-install.ps1 -Version $env:DotNetVersion -InstallDir "$env:ProgramFiles\dotnet\" -Verbose
        & dotnet --list-sdks

    - name: Run maui check
      shell: pwsh
      run: |
        & dotnet tool update --global redth.net.maui.check --version $env:MauiCheckVersion --add-source https://api.nuget.org/v3/index.json
        & maui-check --ci --non-interactive --fix --skip androidsdk --skip xcode --skip vswin --skip vsmac --manifest $env:MauiCheckManifest

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dotnet restore $env:ProjectPath --configfile $env:NuGetConfigPath
      env:
        TELERIK_USERNAME: ${{ secrets.MyTelerikAccountUsername }}
        TELERIK_PASSWORD: ${{ secrets.MyTelerikAccountPassword }}  

    - name: Build Maui project
      shell: pwsh
      run: dotnet build $env:SolutionPath -c $env:BuildConfig --no-restore
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: maui-windows-artifacts
        path: '*Android\**\*-Signed.apk'

